services:
  worker:
    build: .
    networks:
      - app_network
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      MAX_PARALLEL_PROCESSES: ${MAX_PARALLEL_PROCESSES}
      QUEUE_NAME: ${QUEUE_NAME}
    deploy:
      replicas: ${CONTAINER_REPLICAS}
    volumes:
      - ./:/app
      - ${ACCOUNT_SESSION_PATH}:/app/storage/sessions:rw
      - ${ACCOUNT_JSON_PATH}:/app/storage/json:rw
    user: "1000:1001"

    mem_limit: ${CONTAINER_MEM_LIMIT}
    cpus: ${CONTAINER_CPUS}

networks:
  app_network:
    external: true

